In [1]:
from openpyxl import Workbook, load_workbook
from datetime import datetime
import os
import pandas as pd
ACCOUNT_FILE = "accounts.xlsx"
TRANSACTION_FILE = "transactions.xlsx"

# -----------------------------
# Create Excel files if not exist
# -----------------------------

def create_files():

    if not os.path.exists(ACCOUNT_FILE):
        wb = Workbook()
        ws = wb.active
        ws.append(["Account No","Name","PIN","Balance"])
        wb.save(ACCOUNT_FILE)

    if not os.path.exists(TRANSACTION_FILE):
        wb = Workbook()
        ws = wb.active
        ws.append(["Transaction ID","Account No","Type","Amount","Balance","Date"])
        wb.save(TRANSACTION_FILE)

# -----------------------------
# Create Account
# -----------------------------

def create_account():

    name = input("Enter Name: ")
    pin = input("Enter PIN: ")
    balance = float(input("Enter Initial Balance: "))

    wb = load_workbook(ACCOUNT_FILE)
    ws = wb.active

    account_no = ws.max_row

    ws.append([account_no,name,pin,balance])

    wb.save(ACCOUNT_FILE)

    print("\nAccount Created Successfully")
    print("Your Account Number:",account_no)

# -----------------------------
# Login
# -----------------------------

def login():

    acc_no = int(input("Enter Account Number: "))
    pin = input("Enter PIN: ")

    wb = load_workbook(ACCOUNT_FILE)
    ws = wb.active

    for row in ws.iter_rows(min_row=2, values_only=True):

        if row[0] == acc_no and row[2] == pin:
            print("Login Successful")
            return acc_no

    print("Invalid Account or PIN")
    return None

# -----------------------------
# Get Balance
# -----------------------------

def get_balance(acc_no):

    wb = load_workbook(ACCOUNT_FILE)
    ws = wb.active

    for row in ws.iter_rows(min_row=2):
        if row[0].value == acc_no:
            return row[3].value

# -----------------------------
# Update Balance
# -----------------------------

def update_balance(acc_no,new_balance):

    wb = load_workbook(ACCOUNT_FILE)
    ws = wb.active

    for row in ws.iter_rows(min_row=2):
        if row[0].value == acc_no:
            row[3].value = new_balance

    wb.save(ACCOUNT_FILE)

# -----------------------------
# Save Transaction
# -----------------------------

def save_transaction(acc_no,ttype,amount,balance):

    wb = load_workbook(TRANSACTION_FILE)
    ws = wb.active

    tid = ws.max_row

    ws.append([
        tid,
        acc_no,
        ttype,
        amount,
        balance,
        datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ])

    wb.save(TRANSACTION_FILE)

# -----------------------------
# Deposit
# -----------------------------

def deposit(acc_no):

    amount = float(input("Enter amount: "))

    balance = get_balance(acc_no)
    balance += amount

    update_balance(acc_no,balance)
    save_transaction(acc_no,"Deposit",amount,balance)

    print("Deposit Successful")

# -----------------------------
# Withdraw
# -----------------------------

def withdraw(acc_no):

    amount = float(input("Enter amount: "))

    balance = get_balance(acc_no)

    if amount > balance:
        print("Insufficient Balance")
        return

    balance -= amount

    update_balance(acc_no,balance)
    save_transaction(acc_no,"Withdraw",amount,balance)

    print("Withdraw Successful")

# -----------------------------
# Check Balance
# -----------------------------

def check_balance(acc_no):

    balance = get_balance(acc_no)
    print("Current Balance:",balance)

# -----------------------------
# ATM Menu
# -----------------------------

def atm_menu(acc_no):

    while True:

        print("\n----- ATM MENU -----")
        print("1 Deposit")
        print("2 Withdraw")
        print("3 Check Balance")
        print("4 Logout")

        choice = input("Enter choice: ")

        if choice == "1":
            deposit(acc_no)

        elif choice == "2":
            withdraw(acc_no)

        elif choice == "3":
            check_balance(acc_no)

        elif choice == "4":
            break

        else:
            print("Invalid Choice")

# -----------------------------
# Main Program
# -----------------------------

create_files()

while True:

    print("\n==== ATM SYSTEM ====")
    print("1 Create Account")
    print("2 Login")
    print("3 Exit")

    choice = input("Enter choice: ")

    if choice == "1":
        create_account()

    elif choice == "2":

        acc_no = login()

        if acc_no:
            atm_menu(acc_no)

    elif choice == "3":
        print("Thank you for using ATM")
        break

    else:
        print("Invalid choice")

==== ATM SYSTEM ====
1 Create Account
2 Login
3 Exit

Enter choice:  1
Enter Name:  swaraj
Enter PIN:  1234
Enter Initial Balance:  500

Account Created Successfully
Your Account Number: 1

==== ATM SYSTEM ====
1 Create Account
2 Login
3 Exit

Enter choice:  2
Enter Account Number:  1
Enter PIN:  1234

Login Successful

----- ATM MENU -----
1 Deposit
2 Withdraw
3 Check Balance
4 Logout

Enter choice:  1
Enter amount:  300

Deposit Successful

----- ATM MENU -----
1 Deposit
2 Withdraw
3 Check Balance
4 Logout

Enter choice:  3

Current Balance: 800

----- ATM MENU -----
1 Deposit
2 Withdraw
3 Check Balance
4 Logout

Enter choice:  2
Enter amount:  200

Withdraw Successful

----- ATM MENU -----
1 Deposit
2 Withdraw
3 Check Balance
4 Logout

Enter choice:  3

Current Balance: 600

----- ATM MENU -----
1 Deposit
2 Withdraw
3 Check Balance
4 Logout

Enter choice:  4

==== ATM SYSTEM ====
1 Create Account
2 Login
3 Exit

Enter choice:  3

Thank you for using ATM

In [2]:
df=pd.read_excel("accounts.xlsx")
df

   Account No    Name   PIN  Balance
0           1  swaraj  1234      600

In [3]:
dft=pd.read_excel("transactions.xlsx")
dft

   Transaction ID  Account No      Type  Amount  Balance                 Date
0               1           1   Deposit     300      800  2026-03-06 14:55:35
1               2           1  Withdraw     200      600  2026-03-06 14:55:58